global:
  scrape_interval: 15s

scrape_configs:
  # ClickHouse Exporter
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse-exporter:9116']
    scrape_interval: 10s
  # Kafka Exporter
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 10s
  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 10s 
    basic_auth:
      username: '${GRAFANA_PROMETHEUS_USER}'
      password: '${GRAFANA_PROMETHEUS_PASSWORD}'
  # Vector Metrics
  - job_name: 'shipping_vector'
    static_configs:
      - targets: ['log-shipping-vector:8686']
    scrape_interval: 10s
     
  - job_name: 'routing_vector'
    static_configs:
      - targets: ['vector-clickhouse:8687']
    scrape_interval: 10s  