global:
  scrape_interval: 15s

scrape_configs:
  # ClickHouse Exporter
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse-exporter:9116']
    scrape_interval: 10s
  # Kafka Exporter
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 10s